--
-- TOC entry 203 (class 1259 OID 16816)
-- Name: tbl_category; Type: TABLE; Schema: public; Owner: obhadpxyffigpd
--

CREATE TABLE public.tbl_category (
    id integer NOT NULL,
    name character varying(255)
);


ALTER TABLE public.tbl_category OWNER TO obhadpxyffigpd;

--
-- TOC entry 202 (class 1259 OID 16814)
-- Name: tbl_category_id_seq; Type: SEQUENCE; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE public.tbl_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 16821)
-- Name: tbl_payment; Type: TABLE; Schema: public; Owner: obhadpxyffigpd
--

CREATE TABLE public.tbl_payment (
    moment timestamp without time zone,
    purchase_order_id integer NOT NULL
);


ALTER TABLE public.tbl_payment OWNER TO obhadpxyffigpd;

--
-- TOC entry 206 (class 1259 OID 16828)
-- Name: tbl_product; Type: TABLE; Schema: public; Owner: obhadpxyffigpd
--

CREATE TABLE public.tbl_product (
    id integer NOT NULL,
    description character varying(255),
    img_url character varying(255),
    name character varying(255),
    price double precision
);


ALTER TABLE public.tbl_product OWNER TO obhadpxyffigpd;

--
-- TOC entry 207 (class 1259 OID 16836)
-- Name: tbl_product_category; Type: TABLE; Schema: public; Owner: obhadpxyffigpd
--

CREATE TABLE public.tbl_product_category (
    category_id integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.tbl_product_category OWNER TO obhadpxyffigpd;

--
-- TOC entry 205 (class 1259 OID 16826)
-- Name: tbl_product_id_seq; Type: SEQUENCE; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE public.tbl_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16843)
-- Name: tbl_purchaseorder; Type: TABLE; Schema: public; Owner: obhadpxyffigpd
--

CREATE TABLE public.tbl_purchaseorder (
    id integer NOT NULL,
    moment timestamp without time zone,
    purchase_order_status integer,
    client_id integer
);


ALTER TABLE public.tbl_purchaseorder OWNER TO obhadpxyffigpd;

--
-- TOC entry 208 (class 1259 OID 16841)
-- Name: tbl_purchaseorder_id_seq; Type: SEQUENCE; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE public.tbl_purchaseorder ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_purchaseorder_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16848)
-- Name: tbl_purchaseorder_product; Type: TABLE; Schema: public; Owner: obhadpxyffigpd
--

CREATE TABLE public.tbl_purchaseorder_product (
    price double precision,
    quantity integer,
    purchaseorder_id integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.tbl_purchaseorder_product OWNER TO obhadpxyffigpd;

--
-- TOC entry 212 (class 1259 OID 16855)
-- Name: tbl_user; Type: TABLE; Schema: public; Owner: obhadpxyffigpd
--

CREATE TABLE public.tbl_user (
    id integer NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


ALTER TABLE public.tbl_user OWNER TO obhadpxyffigpd;

--
-- TOC entry 211 (class 1259 OID 16853)
-- Name: tbl_user_id_seq; Type: SEQUENCE; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE public.tbl_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2882 (class 0 OID 0)
-- Dependencies: 202
-- Name: tbl_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: obhadpxyffigpd
--

SELECT pg_catalog.setval('public.tbl_category_id_seq', 1, false);


--
-- TOC entry 2883 (class 0 OID 0)
-- Dependencies: 205
-- Name: tbl_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: obhadpxyffigpd
--

SELECT pg_catalog.setval('public.tbl_product_id_seq', 1, false);


--
-- TOC entry 2884 (class 0 OID 0)
-- Dependencies: 208
-- Name: tbl_purchaseorder_id_seq; Type: SEQUENCE SET; Schema: public; Owner: obhadpxyffigpd
--

SELECT pg_catalog.setval('public.tbl_purchaseorder_id_seq', 1, false);


--
-- TOC entry 2885 (class 0 OID 0)
-- Dependencies: 211
-- Name: tbl_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: obhadpxyffigpd
--

SELECT pg_catalog.setval('public.tbl_user_id_seq', 1, false);


--
-- TOC entry 2720 (class 2606 OID 16820)
-- Name: tbl_category tbl_category_pkey; Type: CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_category
    ADD CONSTRAINT tbl_category_pkey PRIMARY KEY (id);


--
-- TOC entry 2722 (class 2606 OID 16825)
-- Name: tbl_payment tbl_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT tbl_payment_pkey PRIMARY KEY (purchase_order_id);


--
-- TOC entry 2726 (class 2606 OID 16840)
-- Name: tbl_product_category tbl_product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_product_category
    ADD CONSTRAINT tbl_product_category_pkey PRIMARY KEY (category_id, product_id);


--
-- TOC entry 2724 (class 2606 OID 16835)
-- Name: tbl_product tbl_product_pkey; Type: CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_product
    ADD CONSTRAINT tbl_product_pkey PRIMARY KEY (id);


--
-- TOC entry 2728 (class 2606 OID 16847)
-- Name: tbl_purchaseorder tbl_purchaseorder_pkey; Type: CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_purchaseorder
    ADD CONSTRAINT tbl_purchaseorder_pkey PRIMARY KEY (id);


--
-- TOC entry 2730 (class 2606 OID 16852)
-- Name: tbl_purchaseorder_product tbl_purchaseorder_product_pkey; Type: CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_purchaseorder_product
    ADD CONSTRAINT tbl_purchaseorder_product_pkey PRIMARY KEY (product_id, purchaseorder_id);


--
-- TOC entry 2732 (class 2606 OID 16862)
-- Name: tbl_user tbl_user_pkey; Type: CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_pkey PRIMARY KEY (id);


--
-- TOC entry 2737 (class 2606 OID 16883)
-- Name: tbl_purchaseorder_product fk4b5wo8jk8xf28rwe1c1xbjf6m; Type: FK CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_purchaseorder_product
    ADD CONSTRAINT fk4b5wo8jk8xf28rwe1c1xbjf6m FOREIGN KEY (purchaseorder_id) REFERENCES public.tbl_purchaseorder(id);


--
-- TOC entry 2736 (class 2606 OID 16878)
-- Name: tbl_purchaseorder fkaqtd5xuefg70ontojep8jt2c6; Type: FK CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_purchaseorder
    ADD CONSTRAINT fkaqtd5xuefg70ontojep8jt2c6 FOREIGN KEY (client_id) REFERENCES public.tbl_user(id);


--
-- TOC entry 2733 (class 2606 OID 16863)
-- Name: tbl_payment fkfq49jrs9bmk757ser88hnt3nu; Type: FK CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_payment
    ADD CONSTRAINT fkfq49jrs9bmk757ser88hnt3nu FOREIGN KEY (purchase_order_id) REFERENCES public.tbl_purchaseorder(id);


--
-- TOC entry 2735 (class 2606 OID 16873)
-- Name: tbl_product_category fkjkbn47tecomukeudhg92tlc15; Type: FK CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_product_category
    ADD CONSTRAINT fkjkbn47tecomukeudhg92tlc15 FOREIGN KEY (category_id) REFERENCES public.tbl_category(id);


--
-- TOC entry 2738 (class 2606 OID 16888)
-- Name: tbl_purchaseorder_product fklih8k10alq6xdewauadt2fuw0; Type: FK CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_purchaseorder_product
    ADD CONSTRAINT fklih8k10alq6xdewauadt2fuw0 FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);


--
-- TOC entry 2734 (class 2606 OID 16868)
-- Name: tbl_product_category fklwd56rummt6sunb6fl3t6002r; Type: FK CONSTRAINT; Schema: public; Owner: obhadpxyffigpd
--

ALTER TABLE ONLY public.tbl_product_category
    ADD CONSTRAINT fklwd56rummt6sunb6fl3t6002r FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);


-- Completed on 2020-05-04 22:47:36

--
-- PostgreSQL database dump complete
--

